task_7/Cleanup build.gradle
DanutaHer/invoicing-system-danuta-hering pull request #11
Opened 2023-07-18 20:54 UTC by szymonone

2023-07-19 13:36 UTC, DanutaHer requested changes

2023-07-19 13:36 UTC, DanutaHer commented on app/build.gradle
> +    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
Proponuję jeszcze zastanowić się nad ilością dependencji bo w Springu jest już jackson i junit i może coś jeszcze, może uda się to usunąć z pliku. Wg. propozycji z zajęć dependencje ułożone są alfabetycznie.

2023-07-19 13:36 UTC, DanutaHer commented on app/build.gradle
>  }
Jest opcja wrzucenia spring framework boot do pluginów:
"Note: Spring Boot Starter dependencies do not have a version specified - it’s controlled by the org.springframework.boot plugin version. It’s another way Spring Boot is making your life easier."

2023-07-19 19:57 UTC, szymonone commented
Do omowienia jutro ;)
Dzięki ;)

śr., 19 lip 2023, 15:36 użytkownik DanutaHer ***@***.***>
napisał:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/build.gradle
> <https://github.com/DanutaHer/invoicing-system-danuta-hering/pull/11#discussion_r1267658660>
> :
>
> > +    implementation "org.projectlombok:lombok:${lombokVersion}"
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: "${springBootVersion}"
> +    implementation "com.google.guava:guava:${guavaVersion}"
> +    implementation "com.fasterxml.jackson.core:jackson-databind:${fasterVersion}"
> +    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${fasterVersion}"
> +
> +    testImplementation group: 'org.springframework.boot', name: 'spring-boot-starter-test', version: "${springBootVersion}"
> +    testImplementation "org.codehaus.groovy:groovy:${groovyVersion}"
> +    testImplementation "org.spockframework:spock-core:${spockVersion}"
> +    testImplementation "junit:junit:${junitVersion}"
> +
> +    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
> +    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
> +    compileOnly "org.projectlombok:lombok:${lombokVersion}"
> +    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
>
> Proponuję jeszcze zastanowić się nad ilością dependencji bo w Springu jest
> już jackson i junit i może coś jeszcze, może uda się to usunąć z pliku. Wg.
> propozycji z zajęć dependencje ułożone są alfabetycznie.
> ------------------------------
>
> In app/build.gradle
> <https://github.com/DanutaHer/invoicing-system-danuta-hering/pull/11#discussion_r1267664926>
> :
>
> >      id 'groovy'
> -
> -    // Apply the application plugin to add support for building a CLI application in Java.
>      id 'application'
>      id 'checkstyle'
>      id 'jacoco'
>  }
>
> Jest opcja wrzucenia spring framework boot do pluginów:
> "Note: Spring Boot Starter dependencies do not have a version specified -
> it’s controlled by the org.springframework.boot plugin version. It’s
> another way Spring Boot is making your life easier."
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DanutaHer/invoicing-system-danuta-hering/pull/11#pullrequestreview-1536435582>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7JCLGXKTSBY23QTAYXY3RTXQ7PGHANCNFSM6AAAAAA2O6BXNM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2023-07-20 21:13 UTC, szymonone commented on app/build.gradle
> +    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
poprawione, pls o weryfikację :)

2023-07-20 21:13 UTC, szymonone commented on app/build.gradle
>  }
poprawione, pls o weryfikację :)

2023-07-21 08:57 UTC, DanutaHer approved these changes, later dismissed

2023-07-23 23:30 UTC, DanutaHer approved these changes

2023-07-24 17:20 UTC, BartoszKamyszek approved these changes

2023-07-31 18:05 UTC, merged