Task 7/spring profiles
DanutaHer/invoicing-system-danuta-hering pull request #19
Opened 2023-07-19 14:40 UTC by DanutaHer

2023-07-22 21:31 UTC, szymonone commented on app/src/main/resources/application.yml
> +      file: invoices.txt
Moim zdaniem sekcję invoicing-system należy usunąć z pliku application ponieważ ma osobne parametry dla dev i prod. w application.yml zostawiajmy tylko wspólne elementy, które będą dziedziczyć dev i prod.

2023-07-24 12:37 UTC, szymonone approved these changes

2023-07-24 12:37 UTC, szymonone approved these changes, later dismissed

2023-07-24 17:13 UTC, BartoszKamyszek requested changes

2023-07-24 17:13 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/db/files/FileDatabase.java
> +      throw new RuntimeException("Failed to update invoice with id: " + id, exception);
Failed to delete

2023-07-24 17:13 UTC, BartoszKamyszek commented on app/src/main/resources/application-prod.yml
> +      file: invoices.txt
tutaj zrobiłbym ścieżke na odwrót, czyli zamiasta id.file i invoices.file to file.id i file.invoices, wtedy masz mniej rozgałęzień w drzewku i jest to też bardziej zrozumiałe przynajmniej dla mnie :)

2023-07-24 19:47 UTC, szymonone approved these changes

2023-07-24 20:36 UTC, szymonone approved these changes

2023-07-26 16:44 UTC, BartoszKamyszek approved these changes

2023-07-31 09:08 UTC, merged