Added configuration @Slf4j
DanutaHer/invoicing-system-danuta-hering pull request #25
Opened 2023-07-24 20:29 UTC by szymonone

2023-07-24 20:40 UTC, DanutaHer approved these changes, later dismissed

2023-07-26 16:48 UTC, BartoszKamyszek requested changes

2023-07-26 16:48 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/controllers/InvoiceController.java
> +    log.info("Get allInvoices: " + allInvoices.size());
te logi nie mówią za dużo, pamiętaj, że log.info ma służyć za pomoc człowiekowi, który przegląda je podczas monitorowania działania aplikacji. Niech będą one bardziej biznesowo- opisowe -> np. Invoice requested by Id: + id,
zwracanie optionala w logach też nie jest najlepsze, bo zamiast danych zwracasz jakieś obiekty javove.

2023-07-26 21:31 UTC, DanutaHer submitted a review, later dismissed

2023-07-27 17:37 UTC, BartoszKamyszek submitted a review, later dismissed

2023-08-03 15:54 UTC, DanutaHer approved these changes

2023-08-03 15:55 UTC, szymonone commented on app/src/main/java/pl/futurecollars/invoicing/controllers/InvoiceController.java
> +    log.info("Get allInvoices: " + allInvoices.size());
cześć, opisy logów poprawione.

2023-08-03 15:59 UTC, merged