Task 10/extending tax calculator
DanutaHer/invoicing-system-danuta-hering pull request #43
Opened 2023-08-23 11:49 UTC by DanutaHer

2023-08-28 05:36 UTC, szymonone approved these changes

2023-08-30 15:56 UTC, BartoszKamyszek requested changes

2023-08-30 15:56 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/service/TaxCalculatorServiceTest.groovy
> +class TaxCalculatorServiceTest extends Specification {
Te testy mogłyby sprawdzać rzeczywistą obliczoną wartość przy zamockowanej bazie danych, a nie tylko użycie tej bazy

2023-08-30 15:56 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/service/TaxCalculatorServiceTest.groovy
> +}
nie dodajemy kodu zakomentowanego, jeżeli jest niepotrzebny to go usuń :)

2023-09-01 11:47 UTC, closed without merging