Task 14/no sql & mongo db
DanutaHer/invoicing-system-danuta-hering pull request #45
Opened 2023-08-29 07:39 UTC by DanutaHer

2023-09-11 11:07 UTC, szymonone submitted a review, later dismissed

2023-09-12 12:52 UTC, BartoszKamyszek requested changes

2023-09-12 12:52 UTC, BartoszKamyszek commented on app/build.gradle
> +    useJUnitPlatform()
2 razy dodane useJunitPlatform()

2023-09-12 14:14 UTC, BartoszKamyszek approved these changes

2023-09-12 14:42 UTC, merged